### PR TITLE
Fix - LONG LIST OF ALL THE SWIFT FILES IN OUR PRESENTATION PACKAGE

### PR DESCRIPTION
**Pull request by BarredEwe**
### Short description 📝
When the number of sources (files) is more than 4096, it gave an error:

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'too many arguments (4220) -- limit is 4096'

### Solution 📦
Now, when starting sourcery, an additional `sourcery.yml` file is generated in the cache folder. This allows you to bypass the restriction.

### CODE REVIEW

**Comment by woutergoossens** [comment]
Screenshot 2024-04-16 at 14 34 06

I am getting this error now.. 
@BarredEwe

**Comment by woutergoossens** [comment]
@BarredEwe The tests in this PR are also failing because of that file..

**Comment by BarredEwe** [comment]
@woutergoossens I have updated the PR. Could you try again?

**Comment by BarredEwe** [comment]
@woutergoossens Hmm. I can't reproduce it(

**Comment by woutergoossens** [comment]
> @woutergoossens Hmm. I can't reproduce it. Could you send me `/Users/gowo/Library/Developer/Xcode/DerivedData/Presentation-gkbvpnlvzvzfoefbirrgyrkvqkzi/SourcePackages/plugins/presentation.output/PresentationPreviewTests/PrefireTestsPlugin/Cache/sourcery-yml` file?

[sourcery.yml.zip](https://github.com/BarredEwe/Prefire/files/15066802/sourcery.yml.zip)

**Comment by woutergoossens** [comment]
@BarredEwe 
Problem is here on line 2129

Screenshot 2024-04-22 at 19 45 17

`while reading .yml '/Users/gowo/Library/Developer/Xcode/DerivedData/Presentation-gkbvpnlvzvzfoefbirrgyrkvqkzi/SourcePackages/plugins/presentation.output/PresentationPreviewTests/PrefireTestsPlugin/Cache/sourcery.yml'. '2129:46: error: scanner: mapping values are not allowed in this context:
              TransferSummaryScreen(viewModel: TransferSummaryPreviewViewModel.withErrorMessage())
                                             ^'Using configuration file at '/Users/gowo/Library/Developer/Xcode/DerivedData/Presentation-gkbvpnlvzvzfoefbirrgyrkvqkzi/SourcePackages/plugins/presentation.output/PresentationPreviewTests/PrefireTestsPlugin/Cache/sourcery.yml'
error: while reading .yml '/Users/gowo/Library/Developer/Xcode/DerivedData/Presentation-gkbvpnlvzvzfoefbirrgyrkvqkzi/SourcePackages/plugins/presentation.output/PresentationPreviewTests/PrefireTestsPlugin/Cache/sourcery.yml'. '2129:46: error: scanner: mapping values are not allowed in this context:
              TransferSummaryScreen(viewModel: TransferSummaryPreviewViewModel.withErrorMessage())`

Any idea?

**Comment by BarredEwe** [comment]
@woutergoossens I will try another solution with a custom installation of source in the .prefer.yml file.

**Comment by woutergoossens** [comment]
> @woutergoossens I will try another solution with a custom installation of source in the .prefer.yml file.

Or I should split up our package in other packages to get rid of the > 4000 swift files limit.. :D

**Comment by BarredEwe** [comment]
@@woutergoossens I pushed another fix. Will you try again? 😅

**Comment by BarredEwe** [comment]
@woutergoossens Then I need to finalize everything and I will post a new release

**Comment by woutergoossens** [comment]
> @woutergoossens Then I need to finalize everything and I will post a new release

Hey @BarredEwe, when do you think I can expect a new release so we can enable our preview tests again? :) THanks!

**Comment by BarredEwe** [comment]
> > @woutergoossens Then I need to finalize everything and I will post a new release
> 
> Hey @BarredEwe, when do you think I can expect a new release so we can enable our preview tests again? :) THanks!

I've almost finished everything. There are several problems with formatting the generated code, but in general everything is solvable. 

PS: The modification came out quite large, so it takes a lot of time (

**Comment by BarredEwe** [comment]
@woutergoossens Could you try this version? 
If everything is OK, then we can make a release)

**Comment by woutergoossens** [comment]
@BarredEwe Thanks! Tested, verified and working 🥳

**Pull request merged**
